import Products from "../Products/Products";

const ProductList = [
  {
    id: 1,
    title: "Apple",
    category: "Fruit",
    image: "https://picsum.photos/200?random=1",
    price: 120,
  },
  {
    id: 2,
    title: "Banana",
    category: "Fruit",
    image: "https://picsum.photos/200?random=2",
    price: 60,
  },
  {
    id: 3,
    title: "Orange",
    category: "Fruit",
    image: "https://picsum.photos/200?random=3",
    price: 100,
  },
  {
    id: 4,
    title: "Mango",
    category: "Fruit",
    image: "https://picsum.photos/200?random=4",
    price: 150,
  },
  {
    id: 5,
    title: "Pineapple",
    category: "Fruit",
    image: "https://picsum.photos/200?random=5",
    price: 90,
  },
  {
    id: 6,
    title: "Potato",
    category: "Vegetable",
    image: "https://picsum.photos/200?random=6",
    price: 40,
  },
  {
    id: 7,
    title: "Tomato",
    category: "Vegetable",
    image: "https://picsum.photos/200?random=7",
    price: 50,
  },
  {
    id: 8,
    title: "Onion",
    category: "Vegetable",
    image: "https://picsum.photos/200?random=8",
    price: 70,
  },
  {
    id: 9,
    title: "Carrot",
    category: "Vegetable",
    image: "https://picsum.photos/200?random=9",
    price: 60,
  },
  {
    id: 10,
    title: "Cabbage",
    category: "Vegetable",
    image: "https://picsum.photos/200?random=10",
    price: 80,
  },
  {
    id: 11,
    title: "Milk",
    category: "Dairy",
    image: "https://picsum.photos/200?random=11",
    price: 75,
  },
  {
    id: 12,
    title: "Cheese",
    category: "Dairy",
    image: "https://picsum.photos/200?random=12",
    price: 220,
  },
  {
    id: 13,
    title: "Butter",
    category: "Dairy",
    image: "https://picsum.photos/200?random=13",
    price: 180,
  },
  {
    id: 14,
    title: "Yogurt",
    category: "Dairy",
    image: "https://picsum.photos/200?random=14",
    price: 90,
  },
  {
    id: 15,
    title: "Cream",
    category: "Dairy",
    image: "https://picsum.photos/200?random=15",
    price: 200,
  },
  {
    id: 16,
    title: "Fish",
    category: "Seafood",
    image: "https://picsum.photos/200?random=16",
    price: 350,
  },
  {
    id: 17,
    title: "Prawn",
    category: "Seafood",
    image: "https://picsum.photos/200?random=17",
    price: 450,
  },
  {
    id: 18,
    title: "Crab",
    category: "Seafood",
    image: "https://picsum.photos/200?random=18",
    price: 500,
  },
  {
    id: 19,
    title: "Lobster",
    category: "Seafood",
    image: "https://picsum.photos/200?random=19",
    price: 800,
  },
  {
    id: 20,
    title: "Squid",
    category: "Seafood",
    image: "https://picsum.photos/200?random=20",
    price: 400,
  },
  {
    id: 21,
    title: "Strawberry",
    category: "Fruit",
    image: "https://picsum.photos/200?random=21",
    price: 250,
  },
  {
    id: 22,
    title: "Guava",
    category: "Fruit",
    image: "https://picsum.photos/200?random=22",
    price: 70,
  },
  {
    id: 23,
    title: "Papaya",
    category: "Fruit",
    image: "https://picsum.photos/200?random=23",
    price: 90,
  },
  {
    id: 24,
    title: "Watermelon",
    category: "Fruit",
    image: "https://picsum.photos/200?random=24",
    price: 150,
  },
  {
    id: 25,
    title: "Litchi",
    category: "Fruit",
    image: "https://picsum.photos/200?random=25",
    price: 300,
  },
  {
    id: 26,
    title: "Capsicum",
    category: "Vegetable",
    image: "https://picsum.photos/200?random=26",
    price: 120,
  },
  {
    id: 27,
    title: "Cauliflower",
    category: "Vegetable",
    image: "https://picsum.photos/200?random=27",
    price: 90,
  },
  {
    id: 28,
    title: "Spinach",
    category: "Vegetable",
    image: "https://picsum.photos/200?random=28",
    price: 50,
  },
  {
    id: 29,
    title: "Beans",
    category: "Vegetable",
    image: "https://picsum.photos/200?random=29",
    price: 100,
  },
  {
    id: 30,
    title: "Cucumber",
    category: "Vegetable",
    image: "https://picsum.photos/200?random=30",
    price: 60,
  },
  {
    id: 31,
    title: "Paneer",
    category: "Dairy",
    image: "https://picsum.photos/200?random=31",
    price: 250,
  },
  {
    id: 32,
    title: "Ghee",
    category: "Dairy",
    image: "https://picsum.photos/200?random=32",
    price: 300,
  },
  {
    id: 33,
    title: "Condensed Milk",
    category: "Dairy",
    image: "https://picsum.photos/200?random=33",
    price: 220,
  },
  {
    id: 34,
    title: "Ice Cream",
    category: "Dairy",
    image: "https://picsum.photos/200?random=34",
    price: 180,
  },
  {
    id: 35,
    title: "Whipped Cream",
    category: "Dairy",
    image: "https://picsum.photos/200?random=35",
    price: 150,
  },
  {
    id: 36,
    title: "Salmon",
    category: "Seafood",
    image: "https://picsum.photos/200?random=36",
    price: 700,
  },
  {
    id: 37,
    title: "Tuna",
    category: "Seafood",
    image: "https://picsum.photos/200?random=37",
    price: 600,
  },
  {
    id: 38,
    title: "Hilsa",
    category: "Seafood",
    image: "https://picsum.photos/200?random=38",
    price: 1000,
  },
  {
    id: 39,
    title: "Catfish",
    category: "Seafood",
    image: "https://picsum.photos/200?random=39",
    price: 350,
  },
  {
    id: 40,
    title: "Shark Meat",
    category: "Seafood",
    image: "https://picsum.photos/200?random=40",
    price: 1200,
  },
  {
    id: 41,
    title: "Peach",
    category: "Fruit",
    image: "https://picsum.photos/200?random=41",
    price: 200,
  },
  {
    id: 42,
    title: "Kiwi",
    category: "Fruit",
    image: "https://picsum.photos/200?random=42",
    price: 300,
  },
  {
    id: 43,
    title: "Pear",
    category: "Fruit",
    image: "https://picsum.photos/200?random=43",
    price: 180,
  },
  {
    id: 44,
    title: "Plum",
    category: "Fruit",
    image: "https://picsum.photos/200?random=44",
    price: 220,
  },
  {
    id: 45,
    title: "Coconut",
    category: "Fruit",
    image: "https://picsum.photos/200?random=45",
    price: 100,
  },
  {
    id: 46,
    title: "Broccoli",
    category: "Vegetable",
    image: "https://picsum.photos/200?random=46",
    price: 140,
  },
  {
    id: 47,
    title: "Pumpkin",
    category: "Vegetable",
    image: "https://picsum.photos/200?random=47",
    price: 120,
  },
  {
    id: 48,
    title: "Radish",
    category: "Vegetable",
    image: "https://picsum.photos/200?random=48",
    price: 60,
  },
  {
    id: 49,
    title: "Eggplant",
    category: "Vegetable",
    image: "https://picsum.photos/200?random=49",
    price: 90,
  },
  {
    id: 50,
    title: "Chili",
    category: "Vegetable",
    image: "https://picsum.photos/200?random=50",
    price: 80,
  },
  {
    id: 51,
    title: "Apricot",
    category: "Fruit",
    image: "https://picsum.photos/200?random=51",
    price: 220,
  },
  {
    id: 52,
    title: "Blackberry",
    category: "Fruit",
    image: "https://picsum.photos/200?random=52",
    price: 280,
  },
  {
    id: 53,
    title: "Cherry",
    category: "Fruit",
    image: "https://picsum.photos/200?random=53",
    price: 300,
  },
  {
    id: 54,
    title: "Dates",
    category: "Fruit",
    image: "https://picsum.photos/200?random=54",
    price: 350,
  },
  {
    id: 55,
    title: "Dragon Fruit",
    category: "Fruit",
    image: "https://picsum.photos/200?random=55",
    price: 500,
  },
  {
    id: 56,
    title: "Sweet Corn",
    category: "Vegetable",
    image: "https://picsum.photos/200?random=56",
    price: 100,
  },
  {
    id: 57,
    title: "Green Peas",
    category: "Vegetable",
    image: "https://picsum.photos/200?random=57",
    price: 90,
  },
  {
    id: 58,
    title: "Bitter Gourd",
    category: "Vegetable",
    image: "https://picsum.photos/200?random=58",
    price: 70,
  },
  {
    id: 59,
    title: "Okra",
    category: "Vegetable",
    image: "https://picsum.photos/200?random=59",
    price: 85,
  },
  {
    id: 60,
    title: "Zucchini",
    category: "Vegetable",
    image: "https://picsum.photos/200?random=60",
    price: 110,
  },
  {
    id: 61,
    title: "Skimmed Milk",
    category: "Dairy",
    image: "https://picsum.photos/200?random=61",
    price: 90,
  },
  {
    id: 62,
    title: "Chocolate Milk",
    category: "Dairy",
    image: "https://picsum.photos/200?random=62",
    price: 120,
  },
  {
    id: 63,
    title: "Blue Cheese",
    category: "Dairy",
    image: "https://picsum.photos/200?random=63",
    price: 350,
  },
  {
    id: 64,
    title: "Mozzarella",
    category: "Dairy",
    image: "https://picsum.photos/200?random=64",
    price: 280,
  },
  {
    id: 65,
    title: "Whey Protein",
    category: "Dairy",
    image: "https://picsum.photos/200?random=65",
    price: 450,
  },
  {
    id: 66,
    title: "Octopus",
    category: "Seafood",
    image: "https://picsum.photos/200?random=66",
    price: 900,
  },
  {
    id: 67,
    title: "Oyster",
    category: "Seafood",
    image: "https://picsum.photos/200?random=67",
    price: 750,
  },
  {
    id: 68,
    title: "Clam",
    category: "Seafood",
    image: "https://picsum.photos/200?random=68",
    price: 600,
  },
  {
    id: 69,
    title: "Anchovy",
    category: "Seafood",
    image: "https://picsum.photos/200?random=69",
    price: 500,
  },
  {
    id: 70,
    title: "Swordfish",
    category: "Seafood",
    image: "https://picsum.photos/200?random=70",
    price: 1300,
  },
  {
    id: 71,
    title: "Rice",
    category: "Grain",
    image: "https://picsum.photos/200?random=71",
    price: 60,
  },
  {
    id: 72,
    title: "Wheat Flour",
    category: "Grain",
    image: "https://picsum.photos/200?random=72",
    price: 55,
  },
  {
    id: 73,
    title: "Oats",
    category: "Grain",
    image: "https://picsum.photos/200?random=73",
    price: 150,
  },
  {
    id: 74,
    title: "Barley",
    category: "Grain",
    image: "https://picsum.photos/200?random=74",
    price: 140,
  },
  {
    id: 75,
    title: "Quinoa",
    category: "Grain",
    image: "https://picsum.photos/200?random=75",
    price: 250,
  },
  {
    id: 76,
    title: "Almond",
    category: "Nut",
    image: "https://picsum.photos/200?random=76",
    price: 700,
  },
  {
    id: 77,
    title: "Cashew",
    category: "Nut",
    image: "https://picsum.photos/200?random=77",
    price: 800,
  },
  {
    id: 78,
    title: "Walnut",
    category: "Nut",
    image: "https://picsum.photos/200?random=78",
    price: 900,
  },
  {
    id: 79,
    title: "Pistachio",
    category: "Nut",
    image: "https://picsum.photos/200?random=79",
    price: 950,
  },
  {
    id: 80,
    title: "Hazelnut",
    category: "Nut",
    image: "https://picsum.photos/200?random=80",
    price: 850,
  },
  {
    id: 81,
    title: "Honey",
    category: "Other",
    image: "https://picsum.photos/200?random=81",
    price: 400,
  },
  {
    id: 82,
    title: "Olive Oil",
    category: "Other",
    image: "https://picsum.photos/200?random=82",
    price: 500,
  },
  {
    id: 83,
    title: "Sunflower Oil",
    category: "Other",
    image: "https://picsum.photos/200?random=83",
    price: 300,
  },
  {
    id: 84,
    title: "Coconut Oil",
    category: "Other",
    image: "https://picsum.photos/200?random=84",
    price: 350,
  },
  {
    id: 85,
    title: "Sugar",
    category: "Other",
    image: "https://picsum.photos/200?random=85",
    price: 90,
  },
  {
    id: 86,
    title: "Green Tea",
    category: "Beverage",
    image: "https://picsum.photos/200?random=86",
    price: 250,
  },
  {
    id: 87,
    title: "Coffee",
    category: "Beverage",
    image: "https://picsum.photos/200?random=87",
    price: 400,
  },
  {
    id: 88,
    title: "Black Tea",
    category: "Beverage",
    image: "https://picsum.photos/200?random=88",
    price: 200,
  },
  {
    id: 89,
    title: "Lemon Juice",
    category: "Beverage",
    image: "https://picsum.photos/200?random=89",
    price: 180,
  },
  {
    id: 90,
    title: "Orange Juice",
    category: "Beverage",
    image: "https://picsum.photos/200?random=90",
    price: 220,
  },
  {
    id: 91,
    title: "Beef",
    category: "Meat",
    image: "https://picsum.photos/200?random=91",
    price: 650,
  },
  {
    id: 92,
    title: "Mutton",
    category: "Meat",
    image: "https://picsum.photos/200?random=92",
    price: 750,
  },
  {
    id: 93,
    title: "Chicken",
    category: "Meat",
    image: "https://picsum.photos/200?random=93",
    price: 350,
  },
  {
    id: 94,
    title: "Turkey",
    category: "Meat",
    image: "https://picsum.photos/200?random=94",
    price: 500,
  },
  {
    id: 95,
    title: "Duck",
    category: "Meat",
    image: "https://picsum.photos/200?random=95",
    price: 450,
  },
  {
    id: 96,
    title: "Eggs",
    category: "Dairy",
    image: "https://picsum.photos/200?random=96",
    price: 120,
  },
  {
    id: 97,
    title: "Tofu",
    category: "Other",
    image: "https://picsum.photos/200?random=97",
    price: 200,
  },
  {
    id: 98,
    title: "Soy Milk",
    category: "Dairy",
    image: "https://picsum.photos/200?random=98",
    price: 150,
  },
  {
    id: 99,
    title: "Mushroom",
    category: "Vegetable",
    image: "https://picsum.photos/200?random=99",
    price: 180,
  },
  {
    id: 100,
    title: "Avocado",
    category: "Fruit",
    image: "https://picsum.photos/200?random=100",
    price: 400,
  },
];

export default ProductList;
